import { useEffect, useState } from 'react';
import { api } from '../lib/api';
import { Button } from '../components/ui';
export function ManagedAccount() {
  const [state,setState]=useState<any>(null),[history,setHistory]=useState<any[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  async function load(){setError('');try{setState(await window.swarm.invoke('account:entitlements'));setHistory((await window.swarm.invoke<any>('account:billing')).transactions);}catch(e){setError(e instanceof Error?e.message:'Account service unavailable.');}}
  useEffect(()=>{void load();const refresh=()=>void load();window.addEventListener('focus',refresh);return()=>window.removeEventListener('focus',refresh);},[]);
  async function preference(profile:string,speed:string){setBusy(true);try{await window.swarm.invoke('account:modelPreferences',profile,speed);await load();}catch(e){setError(e instanceof Error?e.message:'Preference could not be saved.');}finally{setBusy(false);}}
  async function upgrade(){try{await api.account.openWebsite();}catch(e){setError(e instanceof Error?e.message:'Could not open SWARM checkout.');}}
  return <section className="rounded-xl border border-line bg-surface p-5 space-y-3"><h2 className="font-semibold">Managed AI & billing</h2><p className="text-sm">SWARM provides AI through its secure backend. No provider account or API key is needed.</p>{state&&<><p>{state.plan.id==='max'?'SWARM Max':state.plan.id==='pro'?'SWARM Pro':'SWARM Free'} · Builds {state.builds.used}/{state.builds.limit??'unconfigured'} · Chats {state.chats.used}/{state.chats.limit??'unconfigured'}</p><p className="text-xs">Allowance resets {new Date(state.resetsAt).toLocaleString()}{state.plan.id==='pro'?' · Pro expires '+new Date(state.account.pro_until).toLocaleString():''}</p><div className="flex gap-3"><label>Model <select disabled={busy} value={state.account.profile} onChange={e=>void preference(e.target.value,state.account.speed)}>{state.profiles.map((p:any)=><option key={p.id} value={p.id} disabled={!p.available||!p.eligible}>{p.name}{!p.eligible?' · Pro required':!p.available?' · unavailable':''}</option>)}</select></label><label>Generation <select disabled={busy} value={state.account.speed} onChange={e=>void preference(state.account.profile,e.target.value)}>{['fast','balanced','quality'].map(v=><option key={v}>{v}</option>)}</select></label></div><p className="text-sm">Pro: ₹{state.catalog.pro.price/100} · Max: ₹{state.catalog.max?.price/100} INR per 30 days. Manual renewal. Fair-use limits apply.</p></>}<div className="flex gap-2"><Button onClick={()=>void upgrade()}>Plans and billing</Button><Button disabled={busy} onClick={()=>void load()}>Refresh usage</Button></div><h3>Transactions</h3>{history.length?history.map(t=><p className="text-xs break-all" key={t.id}>{new Date(t.created).toLocaleDateString()} · ₹{t.amount/100} INR · {t.status} · {t.id}</p>):<p className="text-xs">No transactions loaded.</p>}{error&&<p role="alert" className="text-sm text-red-600">{error}</p>}</section>;
}
