// Local smoke test of the remote bridge (no Electron): node scripts/remote-smoke.mjs
import { execFile } from 'node:child_process';
import { mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { loadOrCreateCert } from '../electron/remote/cert';
import { DeviceStore } from '../electron/remote/devices';
import { Gateway } from '../electron/remote/gateway';
import { PairingManager } from '../electron/remote/pairing';
import { RemoteServer } from '../electron/remote/server';
import { Ipv6Route, LanRoute, ManualRoute, RouteManager, lanAddresses, globalV6Addresses } from '../electron/remote/routes';
import { connectivityStatus, firewallState, loadConnectivityRoutes, loadConnectivityModule } from '../electron/remote/connectivityHook';
import { FakePhone } from '../tests/helpers/remoteClient';

const projects = [{ id: 'proj_demo', name: 'Delhi Sneaker Store', objective: 'Build a store', status: 'idle', archived: false, updatedAt: Date.now() }];
const invoke = async (ch: string) => (ch === 'projects:list' ? projects : ch === 'runs:active' || ch === 'approvals:list' ? [] : null);
const dir = mkdtempSync(path.join(tmpdir(), 'swarm-smoke-'));
const tls = await loadOrCreateCert(path.join(dir, 'tls.json'));
const pairing = new PairingManager();
const srv = new RemoteServer({ tls, port: 47821, pcName: 'SmokePC', devices: new DeviceStore(path.join(dir, 'd.json')), pairing, gateway: new Gateway(invoke, { pcName: 'SmokePC', appVersion: 'smoke' }), confirmPair: async (i) => { console.log(`PC would ask: Pair "${i.deviceName}"? code ${i.code}`); return true; } });
const port = await srv.start();
console.log(`listening on ${port}; fp=${tls.fingerprint}; LAN=${lanAddresses().join(',')}; IPv6=${globalV6Addresses().join(',') || '-'}`);
// Route layer exactly as electron/remote/index.ts builds it (real connectivity module via the virtual-module hook).
const rm = new RouteManager().add(new LanRoute()).add(new Ipv6Route()).add(new ManualRoute(() => ''));
const ext = await loadConnectivityRoutes({ fingerprint: tls.fingerprint, pcName: 'SmokePC' });
ext.forEach((r) => rm.add(r));
await rm.startAll({ port });
const mod = await loadConnectivityModule();
console.log('connectivity module present:', !!mod, '| providers:', rm.list().map((r) => r.id).join(','));
const cand = mod ? await mod.getCandidateEndpoints!(port) : [];
console.log('module candidates        ->', JSON.stringify(cand));
const hosts = await rm.collectHosts();
console.log('QR hosts                ->', JSON.stringify(hosts), '| all module candidates in hosts:', cand.every((c) => hosts.includes(c)));
console.log('route statuses          ->', JSON.stringify(rm.statuses().map((s) => [s.id, s.state, s.detail])), '| firewall:', firewallState(), '| status?', !!connectivityStatus());
const curl = (args: string[]) => new Promise<string>((res) => execFile('curl.exe', ['-sk', '-i', '-m', '10', ...args], { encoding: 'utf8' }, (err, out) => res(err ? String(err) : out.split(/\r?\n/).filter((l) => /^HTTP|^\{/.test(l)).join(' | '))));
console.log('curl -k GET /v1/ping           ->', await curl([`https://127.0.0.1:${port}/v1/ping`]));
console.log('curl -k GET /v1/agents (no auth) ->', await curl([`https://127.0.0.1:${port}/v1/agents`]));
console.log('curl -k GET /v1/agents (bad auth)->', await curl(['-H', 'Authorization: Bearer abc.def', `https://127.0.0.1:${port}/v1/agents`]));
const phone = new FakePhone(port, tls.fingerprint);
const pr = await phone.request('POST', '/v1/pair', { body: phone.pairBody(pairing.generate().token, 'Smoke Phone') });
console.log('pair (pinned fp)               ->', pr.status, JSON.stringify({ deviceId: pr.json.deviceId, secretLen: pr.json.deviceSecret?.length }));
phone.secret = pr.json.deviceSecret;
const ag = await phone.request('GET', '/v1/agents', { signed: true });
console.log('signed GET /v1/agents          ->', ag.status, JSON.stringify(ag.json));
const ag2 = await phone.request('GET', '/v1/agents', { headers: phone.authHeaders('GET', '/v1/agents', '', { secret: pr.json.deviceSecret }) });
console.log('signed again (fresh nonce)     ->', ag2.status);
await rm.stopAll();
await srv.stop();
console.log('stopped');